name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            cd /opt/rekakebijakan

            git pull origin main

            docker compose -f compose.yaml build --pull

            docker compose -f compose.yaml up -d

            docker compose -f compose.yaml ps
